### ISSUE TITLE
Argparser choices conflict with get_dataset

### ISSUE THREAD

**Issue by p1k0pan** [WangFei-2019/SNARE#1]
In SNARE_probing.py file some given choices like `VG_Attribute_Ownership` have conflicts with the arguments in `datasets_zoo/__init__/get_dataset `, which cause `ValueError: Unknown datasets_zoo VG_Attribute_Ownership`

**Comment by WangFei-2019** [comment]
Thank you for the reminder. We have modified the name of the task in the code (removing "VG -"), but forgot to modify it in the "help" section of the "-- dataset".
