### ISSUE TITLE
When args.model_name is 'blip2', it dosen't have evaluate_vllm_scores function

### ISSUE THREAD

**Issue by p1k0pan** [WangFei-2019/SNARE#2]
My running command is `python SNARE_probing.py --device cuda:0 --model_name blip2  --download --dataset COCO_Semantic_Structure`

Please help me with getting the right evaluation of COCO_Semantic_Structure on Blip2

**Comment by WangFei-2019** [comment]
The "COCO_Semantic_Structure" task destroyed the syntactic structure of the sentence, and it is not appropriate to use the pipeline that evaluates MLLMs (relies on MLM to construct linguistic knowledge distribution) in our paper. Therefore, we did not provide the corresponding code.
